#!/bin/bash
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_65
export PATH=$JAVA_HOME/bin:$PATH

echo 'Building Backend app'

${OPENSHIFT_DATA_DIR}apache-maven-3.3.9/bin/mvn -f ${OPENSHIFT_REPO_DIR}backend/beer-app/pom.xml clean package -DskipTests -s ${OPENSHIFT_REPO_DIR}.openshift/settings.xml

echo 'Booting up'

nohup java -XX:+UseG1GC -Xmx384M -jar -Dspring.datasource.username=${OPENSHIFT_MYSQL_DB_USERNAME} -Dspring.datasource.password=${OPENSHIFT_MYSQL_DB_PASSWORD} -Dspring.datasource.jdbcUrl=jdbc:mysql://${OPENSHIFT_MYSQL_DB_HOST}:${OPENSHIFT_MYSQL_DB_PORT}/beer -Dserver.port=${OPENSHIFT_DIY_PORT} -Dserver.address=${OPENSHIFT_DIY_IP} ${OPENSHIFT_REPO_DIR}backend/beer-app/target/*.jar > ${OPENSHIFT_DIY_LOG_DIR}/java.log 2>&1 &
