-- MySQL Script generated by MySQL Workbench
-- 02/22/17 17:43:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL,
  `Supplier_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `quantity` INT NULL,
  `price_after_discount` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Supplier_idx` (`Supplier_id` ASC),
  CONSTRAINT `fk_Product_Supplier`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `mydb`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `Role_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `house_number` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `tel_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `security_question` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Role1_idx` (`Role_id` ASC),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `mydb`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wrap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wrap` (
  `idwrap` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`idwrap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Package` (
  `id` INT NOT NULL,
  `price` FLOAT NULL,
  `wrap_idwrap` INT NOT NULL,
  PRIMARY KEY (`id`, `wrap_idwrap`),
  INDEX `fk_Package_wrap1_idx` (`wrap_idwrap` ASC),
  CONSTRAINT `fk_Package_wrap1`
    FOREIGN KEY (`wrap_idwrap`)
    REFERENCES `mydb`.`wrap` (`idwrap`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `Package_id` INT NOT NULL,
  `price` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `type_of_payment` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_User1_idx` (`User_id` ASC),
  INDEX `fk_Order_Package1_idx` (`Package_id` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Package1`
    FOREIGN KEY (`Package_id`)
    REFERENCES `mydb`.`Package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Package` (
  `Product_id` INT NOT NULL,
  `Package_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Package_id`),
  INDEX `fk_Product_has_Package_Package1_idx` (`Package_id` ASC),
  INDEX `fk_Product_has_Package_Product1_idx` (`Product_id` ASC),
  CONSTRAINT `fk_Product_has_Package_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Package_Package1`
    FOREIGN KEY (`Package_id`)
    REFERENCES `mydb`.`Package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
